import os,pexpect,sys
os.chdir(os.environ["HOME"]+"/IT/CompetitiveProgramming/HackerEarth/")
os.system("rm *.*~")
os.system("rm *.out")
os.system("rm *.class")
os.system("git add -A")
os.system("git status")
os.system("git commit -m \""+sys.argv[1]+"\"")
git = pexpect.spawn("git push")
git.expect(": ")
git.sendline("your_username")
git.expect(": ")
git.sendline("your_password") 
git.interact()
